### ISSUE TITLE
Some files not uploading

### ISSUE THREAD

**Issue by njbee** [Seji64/GPXRide#1]
I’m getting some files that won’t upload to convert. GitHub won’t accept a gpx file soI can’t upload a sample?

**Comment by Seji64** [comment]
Maybe you can upload it when you put it in a zip archive?

**Comment by njbee** [comment]
[Calais to St Antonin.zip](https://github.com/Seji64/GPXRide/files/7970969/Calais.to.St.Antonin.zip)

Try this one

Nick

**Comment by Seji64** [comment]
Wow, thats a massive file. I assume the file is too big (is printed in the browser console):
`Supplied file with size 828581 bytes exceeds the maximum of 512000 bytes. `

I will have a look if its possible to increase the limit. Maybe it is a github limitation.

**Comment by njbee** [comment]
I could email it to you.  Just checked original gpx file is only 829kb

**Comment by njbee** [comment]
The zip file is only 122kb?

**Comment by Seji64** [comment]
You got me wrong. Your upload is ok. I can work with that. The Blazor App / GPXRide itself has this Limitation. I will try to fix this.

**Comment by njbee** [comment]
Ah I see. It’s a lengthy tour across France so is quite a long journey. The MV app is limited whilst Calimoto makes planning easy. Hope you can fix it.

Thanks

**Comment by Seji64** [comment]
@njbee I fixed the issue. Please try again - Thanks :-)
