### ISSUE TITLE
Mvtrip a gpx

### ISSUE THREAD

**Issue by Leoquiles** [Seji64/GPXRide#4]
Would it be possible to convert the routes recorded in mv ride, in mvtrip format, to gpx? With the intention of being able to export the telemetry in garmin virb? Thanks for all

**Comment by Seji64** [comment]
To be honest i have used the trip record feature only one time. However the `mvtrip `also seems to be just a zip file which contains two `json` files. i took a quick look - seems to be quite possible to generate a gpx file from that data.

**Comment by Seji64** [comment]
Implemented! Please note its in beta state but it should work.

**Comment by Seji64** [comment]
I rewrote the whole thing. The feature is now stable. please ensure to clear all caches,

**Comment by Leoquiles** [comment]
Muchas gracias por tu dedicación

**Comment by Leoquiles** [comment]
disculpa por la molestia, intento cargar el archivo y lanza este error`` Failed to prepare/process TRIP-8-9-23 ´´, he borrado caché como comentaste. Te comento el motivo de pedirte esto: parece ser que en la aplicación virb edit (editor de videos) se puede importar una ruta en formato gpx o fit y mostrar en el video la telemetría de la ruta. si no te importa, te adjunto el archivo con el que estoy intentando usar gpxride ( le he cambiado la extensión de mvtrip a zip para poder adjuntarlo) gracias de nuevo por todo

[TRIP-8-9-23.zip](https://github.com/user-attachments/files/16309895/TRIP-8-9-23.zip)

**Comment by Seji64** [comment]
Hi,

your mvtrip looks diffrent then my testfile 🤔Did you "repack" it or something? Do you have an Android Phone or a Iphone?

**Comment by Seji64** [comment]
...nevermind, should be fixed with e3760a22c3bfc18d0df93685cf2f86e4ead2c516

**Comment by Leoquiles** [comment]
Solo modifiqué la extensión para poder enviartelo, está directamente descargado desde el dashboard de mi moto, mediante la app mv ride. Mi teléfono es android

**Comment by Leoquiles** [comment]
Acabo de intentarlo y funciona perfectamente, te agradezco mucho el esfuerzo, yo por desgracia no se nada de programación y valoro mucho tu trabajo y tu capacidad, de nuevo, gracias
